### ISSUE TITLE
trackPage not working in release app

### ISSUE THREAD

**Issue by karbone4** [GleapSDK/ReactNative-SDK#11]
Hey, I tried to trigger a survey when opening a screen which is called `Developer` : 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/48047952/223434728-c49103b1-4695-4e68-9512-9c97b96da1a7.png">

In order to do it, I added `trackPage` function for `pageView` gleap event. It works great in dev mode, but in release mode, `pageView` gleap event is not working and having value `MainActivity${randomId}`

<img width="622" alt="image" src="https://user-images.githubusercontent.com/48047952/223435296-0a6d6239-750a-48b1-8f47-c67d938ff73c.png">

I have 3 screens : `Developer` / `TechnicalInfos` / `UsefulInfos`. Every time I navigate, there is a log about analytics et we call `Gleap.trackPage(currentRouteName)`.

I don't think it changes anything, but I am using expo-dev-client

**Comment by boehlerlukas** [comment]
Hey @karbone4 

Thanks a lot for sharing this issue. It just got fixed in our latest SDK update: v11.0.0

Best regards,
Lukas
