### ISSUE TITLE
Add support for the react native new architecture

### ISSUE THREAD

**Issue by evelant** [GleapSDK/ReactNative-SDK#16]
react-native-gleapsdk does not work with the react native new architecture enabled. It crashes on app launch with 

```
Exception in HostObject::get for prop 'Gleapsdk': com.facebook.react.internal.turbomodule.core. 
TurboModuleInteropUtils$ParsingException: Unable to parse @ReactMethod annotation from native module method: 
    Gleapsdk.registerConfigLoadedAction(). 
Details: Unable to parse JNI signature. Detected unsupported parameter in class: 
    io.gleap.callbacks.ConfigLoadedCallback
```

Gleap is the only dependency left in my project that is lagging behind and does not support the new architecture yet. Please fix this as soon as possible! We would like to transition to the new architecture as it will soon become the default. When it becomes the default Gleap will cease to function entirely on react native. 

Docs about making your library compatible are here: https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-libraries.md

**Comment by boehlerlukas** [comment]
Hey @evelant!

The issue just got fixed. We first tried to upgrade the whole SDK to the new architecture (which comes with lot's of pitfalls). Right now new arch is still in beta and the appropriate way is to rely on the Interop layer. v14.0.1 fixed the issue with the Interop layer and should now allow to fully use it with new arch. One thing to note, there are quite many issues open in terms of new arch - I'd recommend "react-native": "0.75.3" or later as it includes needed fixes in terms of compatibility with our SDK.
