### ISSUE TITLE
Using setTicketAttribute doesn't get reset after a form submission

### ISSUE THREAD

**Issue by itajenglish** [GleapSDK/ReactNative-SDK#19]
Steps to reproduce:
- setTicketAttribute on form A
- Submit form A
- setTicketAttribute on form B
- Submit form B
- Observe form B's ticket including data added from form A

Possible solution:
The data should be reset after a form submission and/or a method to clear ticket attribute data should be added

**Comment by boehlerlukas** [comment]
Hey @itajenglish,

Thanks a lot for reporting! Righ now this is actually the intended behaviour as many customers want to store some more general attributes that should live longer than one report.

What you could do to reset the attributes when a ticket gets reported with this:

Gleap.registerListener('feedbackSent', (data) => {
    // Feedback has been sent with data.
   // Reset attributes now.
});

**Comment by itajenglish** [comment]
Hey @boehlerlukas,

I tried the code below but it crashes the app. I also tried setting the value to an empty string and that only sets the values of the fields to empty not remove them from the ticket.

```
Gleap.registerListener('feedbackSent', (data) => {
  // * Reset all form data attributes
  Object.keys(data.formData).forEach((key) => {
    Gleap.setTicketAttribute(key, null);
  });
});
```

**Comment by boehlerlukas** [comment]
Hey 👋 can you try setting them to undefined? This should remove them.

**Comment by itajenglish** [comment]
Setting it to **undefined** also crashes the app

**Comment by itajenglish** [comment]
Here is the error from [Sentry](https://listedb.sentry.io/share/issue/ae05aefbfff043f2a07eb28dc927ae8e/)

**Comment by boehlerlukas** [comment]
Thanks for sharing! The team will look into this right next week!

**Comment by itajenglish** [comment]
Hey @boehlerlukas, Any updates on this?

**Comment by itajenglish** [comment]
Hey @boehlerlukas Bumping this one more time in case it got lost.

**Comment by boehlerlukas** [comment]
@itajenglish soooory! It got lost. Looking into it today :)

**Comment by boehlerlukas** [comment]
Hey @itajenglish :)

Good news, v14.1.0 now introduces two new methods exactly for unsetting ticket attributes:
http://localhost:3002/reactnative/ticket-attributes#unset-ticket-attributes

Best,
Lukas
