### ISSUE TITLE
Add dev mode

### ISSUE THREAD

**Issue by itajenglish** [GleapSDK/ReactNative-SDK#2]
Add ability to disable gleap from showing widget when opening React Native debugger menu.

https://user-images.githubusercontent.com/889564/159640386-ea7635c0-75a1-4b1f-bb49-4cb59a2d0ff9.mp4

**Comment by niklasfessler** [comment]
Dear @itajenglish,

thanks for your feedback. We're going to check that internal and let you know :) 

Greetings Niklas

**Comment by itajenglish** [comment]
Thank you @niklasfessler
Hi @boehlerlukas, So I did try this and I don't think it worked. I'll try again! Maybe the SDK didn't update.

**Comment by boehlerlukas** [comment]
@itajenglish you are welcome! Please make sure that you also update the native dependencies with `pod install` as the native update is required for this to work. Let me know if it still doesn't work, happy to debug into this :)

**Comment by itajenglish** [comment]
FYI: I found pressing the esc key after it opens, prevents it from opening again until the app is closed and restarted in the simulator.

**Comment by boehlerlukas** [comment]
Great catch @itajenglish! Is this related to the RN SDK or to the JS SDK? I don't have an ESC button on my phone, so it might be related to the simulator? Happy to open another issue for this :)

**Comment by itajenglish** [comment]
RN SDK, When testing using the iOS simulator.
---
OS: iOS 15.4
Device: iPhone 13
Gleap SDK Version: 6.4.4

**Comment by itajenglish** [comment]
> @itajenglish you are welcome! Please make sure that you also update the native dependencies with `pod install` as the native update is required for this to work. Let me know if it still doesn't work, happy to debug into this :)

Still experiencing the same issue.

**Comment by boehlerlukas** [comment]
@itajenglish thanks for the update! We will have another look right tomorrow morning.

**Comment by itajenglish** [comment]
@boehlerlukas Did you have a chance to look into this?

**Comment by boehlerlukas** [comment]
@itajenglish sorry for the delay and thanks for the ping :) We could reproduce the issue. A fix will be available today.

**Comment by boehlerlukas** [comment]
Hey @itajenglish :)

+ react-native-gleapsdk@6.4.8 should now finally fix both issues. Please not that you also need to run `pod update`. Let me know if the fix works for you as well.

**Comment by itajenglish** [comment]
@boehlerlukas Awesome! Thanks for the update!
