### ISSUE TITLE
Sdk is not working in andorid and ios platform

### ISSUE THREAD

**Issue by swatisaingar** [GleapSDK/ReactNative-SDK#5]
In ios while we are shaking our phone at that time we are able to see gleap popup , it means its not working in release build.

In Android , after the installation its showing the errors like -  AAPT: error: resource android:color/system_neutral1_1000 not found.

Followed all the instructions from the documentation -

Code is - 
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import Gleap from "react-native-gleapsdk";

Gleap.initialize('API_Key');

AppRegistry.registerComponent(appName, () => App);

**Comment by swatisaingar** [comment]
React Native Version - 0.68.1
Iphone 13 (Simulator)
Android - app is not running because of errors

**Comment by swatisaingar** [comment]
Is this library supported only in debug mode or we can use this in release build? Please Confirm

**Comment by swatisaingar** [comment]
Thanks for the update

In the web we are adding one script and it will show a feedback button automatically but other side in app we dont have this functionality , so do we have to add button in all the screen for that feedback popup.

**Comment by boehlerlukas** [comment]
Hey @swatisaingar ,

The feedback button is only available for our Web SDK. For our native SDKs we do only support SHAKE and SCREENSHOT by default. In addition to that you can easily add a custom button yourself and then simply call Gleap.open(); to show the widget by code.

Best regards,
Lukas

**Comment by boehlerlukas** [comment]
@swatisaingar regarding the iOS issue: we couldn't reproduce it yet. Do you still experience it? Can you check if you have the correct API key assigned. In addition to that, you must have a valid internet connection for Gleap to open - maybe it was a temporary issue with the network connection?

**Comment by LucaB01** [comment]
@swatisaingar we have updated our react-native sdk: 

7.0.4

Please check out the new version and let me know if you have any further questions.
